#ifndef __PARSECMDMQTT_H__
#define __PARSECMDMQTT_H__

#include <stdint.h>

enum
{
	ROBOCLAW_R2O_SET_CODEUR_M1_VALUE = 1,
	ROBOCLAW_R2O_SET_CODEUR_M2_VALUE,

	ROBOCLAW_R2O_SET_MOTOR_M1_ACC,
	ROBOCLAW_R2O_SET_MOTOR_M1_D,
	ROBOCLAW_R2O_SET_MOTOR_M1_I,
	ROBOCLAW_R2O_SET_MOTOR_M1_P,
	ROBOCLAW_R2O_SET_MOTOR_M1_QPPS,
	ROBOCLAW_R2O_SET_MOTOR_M1_SPEED_ORDER,
	ROBOCLAW_R2O_SET_MOTOR_M1_SPEED_VALUE,

	ROBOCLAW_R2O_SET_MOTOR_M2_ACC,
	ROBOCLAW_R2O_SET_MOTOR_M2_D,
	ROBOCLAW_R2O_SET_MOTOR_M2_I,
	ROBOCLAW_R2O_SET_MOTOR_M2_P,
	ROBOCLAW_R2O_SET_MOTOR_M2_QPPS,
	ROBOCLAW_R2O_SET_MOTOR_M2_SPEED_ORDER,
	ROBOCLAW_R2O_SET_MOTOR_M2_SPEED_VALUE,

	ROBOCLAW_O2R_SET_CODEUR_M1_VALUE,
	ROBOCLAW_O2R_SET_CODEUR_M2_VALUE,

	ROBOCLAW_O2R_SET_MOTOR_M1_ACC,
	ROBOCLAW_O2R_SET_MOTOR_M1_D,
	ROBOCLAW_O2R_SET_MOTOR_M1_I,
	ROBOCLAW_O2R_SET_MOTOR_M1_P,
	ROBOCLAW_O2R_SET_MOTOR_M1_QPPS,
	ROBOCLAW_O2R_SET_MOTOR_M1_SPEED_ORDER,
	ROBOCLAW_O2R_SET_MOTOR_M1_SPEED_VALUE,

	ROBOCLAW_O2R_SET_MOTOR_M2_ACC,
	ROBOCLAW_O2R_SET_MOTOR_M2_D,
	ROBOCLAW_O2R_SET_MOTOR_M2_I,
	ROBOCLAW_O2R_SET_MOTOR_M2_P,
	ROBOCLAW_O2R_SET_MOTOR_M2_QPPS,
	ROBOCLAW_O2R_SET_MOTOR_M2_SPEED_ORDER,
	ROBOCLAW_O2R_SET_MOTOR_M2_SPEED_VALUE,

	ROBOCLAW_R2O_GET_CODEUR_M1_VALUE,
	ROBOCLAW_R2O_GET_CODEUR_M2_VALUE,

	ROBOCLAW_R2O_GET_MOTOR_M1_ACC,
	ROBOCLAW_R2O_GET_MOTOR_M1_D,
	ROBOCLAW_R2O_GET_MOTOR_M1_I,
	ROBOCLAW_R2O_GET_MOTOR_M1_P,
	ROBOCLAW_R2O_GET_MOTOR_M1_QPPS,
	ROBOCLAW_R2O_GET_MOTOR_M1_SPEED_ORDER,
	ROBOCLAW_R2O_GET_MOTOR_M1_SPEED_VALUE,

	ROBOCLAW_R2O_GET_MOTOR_M2_ACC,
	ROBOCLAW_R2O_GET_MOTOR_M2_D,
	ROBOCLAW_R2O_GET_MOTOR_M2_I,
	ROBOCLAW_R2O_GET_MOTOR_M2_P,
	ROBOCLAW_R2O_GET_MOTOR_M2_QPPS,
	ROBOCLAW_R2O_GET_MOTOR_M2_SPEED_ORDER,
	ROBOCLAW_R2O_GET_MOTOR_M2_SPEED_VALUE,

	ROBOCLAW_O2R_GET_CODEUR_M1_VALUE,
	ROBOCLAW_O2R_GET_CODEUR_M2_VALUE,

	ROBOCLAW_O2R_GET_MOTOR_M1_ACC,
	ROBOCLAW_O2R_GET_MOTOR_M1_D,
	ROBOCLAW_O2R_GET_MOTOR_M1_I,
	ROBOCLAW_O2R_GET_MOTOR_M1_P,
	ROBOCLAW_O2R_GET_MOTOR_M1_QPPS,
	ROBOCLAW_O2R_GET_MOTOR_M1_SPEED_ORDER,
	ROBOCLAW_O2R_GET_MOTOR_M1_SPEED_VALUE,

	ROBOCLAW_O2R_GET_MOTOR_M2_ACC,
	ROBOCLAW_O2R_GET_MOTOR_M2_D,
	ROBOCLAW_O2R_GET_MOTOR_M2_I,
	ROBOCLAW_O2R_GET_MOTOR_M2_P,
	ROBOCLAW_O2R_GET_MOTOR_M2_QPPS,
	ROBOCLAW_O2R_GET_MOTOR_M2_SPEED_ORDER,
	ROBOCLAW_O2R_GET_MOTOR_M2_SPEED_VALUE,

	ROBOCLAW_O2R_VERIFY_CMD_LENGTH,
};

uint32_t getIdFrom ( const char * str );

#endif